version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=redis
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - redis

  worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python worker.py
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=redis
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  redis_data: 